In [1]:
import numpy as np
import os 
import matplotlib.pyplot as plt
import h5py 
from tqdm import tqdm

/home/brats/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
def plotter(flair, t2,t1ce,t1,label, mask):
    plt.subplot(1,6,1)
    plt.imshow(flair,cmap='gray')
    plt.subplot(1,6,2)
    plt.imshow(t2,cmap='gray')    
    plt.subplot(1,6,3)
    plt.imshow(t1ce,cmap='gray')    
    plt.subplot(1,6,4)
    plt.imshow(t1,cmap='gray')    
    plt.subplot(1,6,5)
    plt.imshow(label,cmap='gray')
    plt.subplot(1,6,6)
    plt.imshow(mask,cmap='gray')
    plt.show()
    
def get_stats(flair, t2,t1ce,t1,label, mask):
    
    flair_mean = np.nanmean(flair[np.where(mask!=0)])
    flair_std = np.nanstd(flair[np.where(mask!=0)]) 
    
    t2_mean = np.nanmean(t2[np.where(mask!=0)])
    t2_std = np.nanstd(t2[np.where(mask!=0)])   
    
    t1ce_mean = np.nanmean(t1ce[np.where(mask!=0)])
    t1ce_std = np.nanstd(t1ce[np.where(mask!=0)]) 
    
    t1_mean = np.nanmean(t1[np.where(mask!=0)])
    t1_std = np.nanstd(t1[np.where(mask!=0)]) 
    
    mean = [flair_mean, t2_mean,t1ce_mean,t1_mean]
    std =  [flair_std, t2_std,t1ce_std,t1_std]  
    return mean, std
def read_hdf5_and_return_stats(data_path):
    data = h5py.File(data_path,'r')
    mr_sequences= data['Sequence'][:]
    labels      = data ['label'][:]
    mask        = data['mask'][:]
    flair       = mr_sequences[:,:,0]/255
    t2          = mr_sequences[:,:,1]/255
    t1ce        = mr_sequences[:,:,2]/255
    t1          = mr_sequences[:,:,3]/255
    
    #plotter (flair, t2,t1ce,t1,labels, mask)
    mean, std= get_stats(flair, t2,t1ce,t1,labels, mask)
#     print ('Mean',mean)
#     print ('Std', std)
    return mean, std
    
    

In [3]:
path= '/media/brats/MyPassport/Avinash/Kaminstas_2018/MICCAI_BraTS_2018_Data_Training/hdf5_data_0_255/train_set'
files = os.listdir(path)
cntr=0
mean_list= []
std_list = []
for f in tqdm(files):
    mean, std = read_hdf5_and_return_stats(path+'/'+f)
    mean_list.append(mean)
    std_list.append(std)
    cntr+=1
#     if cntr>2:
#         break
print (cntr)

  0%|          | 17/22225 [00:01<39:37,  9.34it/s] /home/brats/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: RuntimeWarning: Mean of empty slice
/home/brats/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1434: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/home/brats/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:21: RuntimeWarning: Mean of empty slice
/home/brats/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:24: RuntimeWarning: Mean of empty slice
/home/brats/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:27: RuntimeWarning: Mean of empty slice
100%|██████████| 22225/22225 [28:37<00:00, 12.94it/s]

22225


In [4]:
mean_array = np.array(mean_list)
std_array  =np.array(std_list)



In [12]:
print (np.nanmean( mean_array,0))
print (np.nanmean(std_array,0))

[0.4465654  0.39885548 0.382155   0.6104794 ]
[0.1427262  0.14297858 0.09494335 0.13883562]


In [ ]:
np.savetxt('')

In [9]:
path= '/media/brats/MyPassport/Avinash/Kaminstas_2018/MICCAI_BraTS_2018_Data_Training/hdf5_data_0_255/valid_set'
files = os.listdir(path)
cntr=0
vmean_list= []
vstd_list = []
for f in tqdm(files):
    mean, std = read_hdf5_and_return_stats(path+'/'+f)
    vmean_list.append(mean)
    vstd_list.append(std)
    cntr+=1
#     if cntr>2:
#         break
print (cntr)

  1%|          | 59/4732 [00:04<05:26, 14.32it/s]/home/brats/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: RuntimeWarning: Mean of empty slice
/home/brats/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1434: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/home/brats/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:21: RuntimeWarning: Mean of empty slice
/home/brats/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:24: RuntimeWarning: Mean of empty slice
/home/brats/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:27: RuntimeWarning: Mean of empty slice
100%|██████████| 4732/4732 [04:52<00:00, 16.19it/s]

4732


In [10]:
np.nanmean(np.array(vmean_list),0)


array([0.46063721, 0.37187726, 0.37342142, 0.62035292])

In [11]:
np.nanmean(np.array(vstd_list),0)

array([0.13994554, 0.13648251, 0.09299794, 0.14201602])