In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt
import h5py
# from sklearn.utils import shuffle
from tqdm import tqdm_notebook as tqdm
import nibabel as nib
import pandas as pd

/home/uavws/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
H5_PATH_TRAIN     = '/media/brats/0d4a2225-d6b1-4b80-94fd-7c8ae0b1fa102/varghese/brats_2018/data/hdf5_data_zscores/train_set'
H5_PATH_VALID     = '/media/brats/0d4a2225-d6b1-4b80-94fd-7c8ae0b1fa102/varghese/brats_2018/data/hdf5_data_zscores/valid_set'

In [ ]:
IDS = next(os.walk(H5_PATH_TRAIN))[2]
nclass = 5 # 0, 1, 2, 4, 5

weights  = np.zeros(nclass)

for id_ in tqdm(IDS):
    path = os.path.join(H5_PATH_TRAIN, id_)
    h5   = h5py.File(path, 'r')
    gt   = np.uint8(h5['label'][:])
    gt[gt == 4] = 3
    gt[gt == 5] = 4
    for i in range(nclass):
        weights[i] += np.sum(gt==i)

In [ ]:
print (weights)
print (np.median(weights)/weights)

## Brain Slice Stat
weights = [1.25493753e+09 5.67836900e+06 1.14197870e+07 3.67903400e+06
 2.61974879e+08]


np.median(weights)/weights = [0.00909988 2.01110336 1.         3.10401779 0.04359115]

In [3]:
IDS = next(os.walk(H5_PATH_TRAIN))[2]
nclass = 2 # 0, 1, 2, 4, 5

weights  = np.zeros(nclass)

for id_ in tqdm(IDS):
    path = os.path.join(H5_PATH_TRAIN, id_)
    h5   = h5py.File(path, 'r')
    gt   = np.uint8(h5['label'][:])
#     gt[gt == 4] = 3
    gt[gt == 2] = 0
    gt[gt == 5] = 0
    gt[gt != 0 ] = 1
    for i in range(nclass):
        weights[i] += np.sum(gt==i)
        
print (weights)
print (np.median(weights)/weights)

HBox(children=(IntProgress(value=0, max=13183), HTML(value='')))


[7.49983397e+08 9.35740300e+06]
[ 0.50623841 40.57433457]


## Brain Slice Stat
weights = [2.70604082e+08 7.52659000e+05 2.50778600e+06 6.26112000e+05
 5.69973610e+07]


np.median(weights)/weights = [0.00926736 3.33190196 1.         4.00533131 0.04399828]

In [4]:
H5_PATH_TRAIN     = '/home/uavws/pranjal/MICCAI_BraTS_2018_Data_Training/'
# type_ = ['HGG_64_cubes', 'LGG_64_cubes']
type_ = ['HGG_64_cubes']
# type_ = ['HGG_patches']
nclass = 5 # 0, 1, 2, 4, 5
weights  = np.zeros(nclass)

for ty in type_:
    ty_path = os.path.join(H5_PATH_TRAIN, ty)
    IDS = next(os.walk(ty_path))[1]
    for id_ in tqdm(IDS):
        path = os.path.join(ty_path, id_)
        patch_IDS = next(os.walk(path))[1]
        for patch in patch_IDS:
            gt = np.uint8(nib.load(os.path.join(path, patch, 'seg_64cube.nii.gz')).get_data())
            gt[gt == 4] = 3
            gt[gt == 5] = 4
            for i in [0, 1, 2, 3, 4]:
                weights[i] += np.sum(gt==i)

HBox(children=(IntProgress(value=0, max=204), HTML(value='')))

/home/uavws/anaconda3/lib/python3.6/site-packages/tqdm/_monitor.py:89: TqdmSynchronisationWarning: Set changed size during iteration (see https://github.com/tqdm/tqdm/issues/481)
  TqdmSynchronisationWarning)


In [5]:
print (weights)
print (np.median(weights))
print (np.median(weights)/weights)

[3.95811782e+09 1.02368486e+09 1.51986758e+09 9.38536437e+08
 7.26397455e+09]
1519867581.0
[0.38398745 1.48470261 1.         1.61940178 0.2092336 ]


/home/uavws/anaconda3/lib/python3.6/site-packages/tqdm/_monitor.py:89: TqdmSynchronisationWarning: Set changed size during iteration (see https://github.com/tqdm/tqdm/issues/481)
  TqdmSynchronisationWarning)


## Brain Vol Stat (9x9x9)
weights = [ 629122. 7922393. 5211280. 3682896. 8929529.]


np.median(weights)/weights = [8.28341721 0.65779115 1.         1.41499516 0.58360077]

In [3]:
H5_PATH_TRAIN='/media/brats/0d4a2225-d6b1-4b80-94fd-7c8ae0b1fa102/varghese/brats_2018/data/hdf5_TC_data_zscore/train_set'
IDS = next(os.walk(H5_PATH_TRAIN))[2]
nclass = 3 # 0, 1, 2, 4, 5

weights  = np.zeros(nclass)

for id_ in tqdm(IDS):
    path = os.path.join(H5_PATH_TRAIN, id_)
    h5   = h5py.File(path, 'r')
    gt   = np.uint8(h5['label'][:])
    
#     gt[gt == 4] = 3
#     gt[gt == 2] = 0
#     gt[gt == 5] = 0
#     gt[gt != 0 ] = 1
    for i in range(nclass):
        weights[i] += np.sum(gt==i)
        
print (weights)
print (np.median(weights)/weights)

H5_PATH_TRAIN='/media/brats/0d4a2225-d6b1-4b80-94fd-7c8ae0b1fa102/varghese/brats_2018/data/hdf5_TC_data_zscore/valid_set'
IDS = next(os.walk(H5_PATH_TRAIN))[2]
nclass = 3 # 0, 1, 2, 4, 5

weights  = np.zeros(nclass)

for id_ in tqdm(IDS):
    path = os.path.join(H5_PATH_TRAIN, id_)
    h5   = h5py.File(path, 'r')
    gt   = np.uint8(h5['label'][:])
    
#     gt[gt == 4] = 3
#     gt[gt == 2] = 0
#     gt[gt == 5] = 0
#     gt[gt != 0 ] = 1
    for i in range(nclass):
        weights[i] += np.sum(gt==i)
        
print (weights)
print (np.median(weights)/weights)

HBox(children=(IntProgress(value=0, max=11914), HTML(value='')))


[6.65889535e+08 1.13994530e+07 8.95741200e+06]
[0.01711914 1.         1.27262796]


HBox(children=(IntProgress(value=0, max=2552), HTML(value='')))


[1.4312498e+08 2.5039570e+06 1.3662630e+06]
[0.0174949  1.         1.83270498]
